- name: create user for execution
  sudo: yes
  user: name=registrolivre group=admin

- name: add PPA repository for open JDK
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: install JDK and related packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
   - software-properties-common
   - python-software-properties
   - openjdk-8-jdk

- name: create registrolivre service
  sudo: yes
  copy: src=../files/app-service.sh dest=/etc/init.d/registrolivre mode=u+rx

- name: create registrolivre .profile (shouldnt the app do it?)
  file: path=/home/registrolivre/.profile state=touch owner=registrolivre

- name: create registrolivre directory (shouldnt the app do it?)
  file: path=/home/registrolivre/app state=directory owner=registrolivre

#- name: do the deploy (UGLY WORKAROUND!!!!!)
#  copy: src=../../../../../build/libs/registrolivre.jar dest=/home/registrolivre/app/registrolivre.jar

- name: enable registrolivre service
  sudo: yes
  service: name=registrolivre state=started enabled=yes

