VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.33.71"
  config.vm.network "forwarded_port", guest: 8080, host: 5000
    #  config.ssh.username = "registrolivre"

  config.vm.define "registrolivre" do |rl|
  end

  config.vm.provider "virtualbox" do |box|
    box.name = "registrolivre"
    box.memory = 2048
    box.cpus = 2
  end

  config.vm.synced_folder "public_keys/", "/home/public_keys", create: true
  config.vm.synced_folder "../../", "/home/registrolivre/registrolivre", create: true

  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "app.yml"
  end

  # Provision
  #config.vm.provision :shell, :path => "../scripts/provision/firefox.sh"
  #config.vm.provision :shell, :path => "../scripts/provision/xvfb.sh"
  #config.vm.provision :shell, :path => "../scripts/provision/functional-test-dependencies.sh"
  config.vm.provision :shell, :path => "scripts/provision/ssh-user-permission.sh"
  #config.vm.provision :shell, :path => "scripts/provision/create-folders.sh"
  config.vm.provision :shell, :path => "scripts/provision/local/configure-database-environment-variable.sh"
end
